
server:
  address: 192.168.0.176
  port: 8002

spring:
  application:
    name: my-second-service

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://192.168.0.176:8761/eureka