
server:
  address: 192.168.0.176
  port: 8000

spring:
  application:
    name: my-zuul-service

zuul:
  routes:
    first-service:
      path: /first-service/**
      url: http://192.168.0.176:8081
    second-service:
      path: /second-service/**
      url: http://192.168.0.176:8082